<!DOCTYPE html>
<html lang="en">

<head>
    <title>Document</title>
</head>

<body>

</body>
<script>
    // 1st Promise
    //              new Promise().then().catch().finally()      <=== syntax of Promise

    const promiseOne = new Promise(function (resolve, reject) {
        setTimeout(function () {
            console.log("1st Async task is completed");
            resolve();
        }, 1000)
    });
    promiseOne.then(function () {
        console.log("1st Promise comsumed!");
    })




    // 2nd Promise
    new Promise(function (resolve, reject) {
        setTimeout(function () {
            console.log("2nd Async task is completed")
            resolve();
        }, 1000)
    }).then((e) => {
        console.log("2nd Promise Consumed!");
    })






    // 3rd Promise
    new Promise(function (resolve, reject) {
        setTimeout(function () {
            console.log("3rd Asyn task is completed");
            resolve({ username: "shehroz", email: "Sheh_140@gmail.com" });
        }, 1000)
    }).then(function (user) {
        console.log(user);
    })







    // 4rth Promise
    const promiseFour = new Promise(function (resolve, reject) {
        setTimeout(function () {
            let error = true;

            if (!error) {
                resolve({ username: "Shehroz Ali", id: 126 });
            }
            else {
                reject("Error: something went wrong!");
            }
        }, 1000)
    });
    promiseFour.then(function (user) {
        console.log(user);
        return user.username;
    }).then(function (username) {
        console.log("Username: ", username);
    }).catch(function (error) {
        console.log(error);
    }).finally(function () {
        console.log(`the promise is either resolved or rejected!`);

    })






    // ^_____ you can solve your problem by .then() and .catch() methods
    // v------- you can also use "async and await" by "try and cath" block keywords for solving same problem. as you want you can use.





    // 5th Promis
    const promiseFive = new Promise(function (resolve, reject) {
        setTimeout(function () {
            const error = true; // <---- true || false
            if (!error) {
                resolve({ username: "Javascript", password: "@Public12#" });
            }
            else {
                reject("Error: Javascript went wrong!");
            }
        }, 1000)
    });
    // v------ ''consume' ka mtlb k call kis trhan krni hai. yani k data kis trha get krna hai get krny ka method ko consume kahty
    async function consumePromiseFive() {
        // const response = await promiseFive;
        // console.log(response);
        try {
            const response = await promiseFive;
            console.log(response);
        }
        catch (error) {
            console.log(error);

        }
    }
    consumePromiseFive();





    // 6th Return promise without try catch block and this is not working ✘ to converting Array to Json formate
    // This concept convert Array formate into JSON formate that return Promise
    async function getCompleteData() {
        const response = await fetch("https://api.github.com/users/Shehroz-Ali-61");
        const datas = await response.json(); // <== this concept convert Array formate into JSON formate that return Promise
        console.log(datas);
    }
    // getCompleteData();





    // 7th Promise by try catch block this is working successfully ✔
    async function getCompleteData() {
        try {
            const response = await fetch("https://api.github.com/users/Shehroz-Ali-61");
            const datas = await response.json(); // <== this concept convert Array formate into JSON formate that return Promise
            console.log(datas);
        }
        catch (error) {
            console.log(error);
        }
    }
    // getCompleteData()






    // 8th fetch() is also a promise. this is used as a promise. fetch b promise ki trhan he kam krta hai jb keese URL sy data lena ho to 
    fetch(("https://api.github.com/users/Shehroz-Ali-61"))
    .then(function(response){
        return response.json();
    })
    .then(function(data){
        console.log(data);
    })
    .catch(function(error){
        console.log(error);
    })

</script>

</html>








<!--
<script>
    /*const promiceFirst = new Promise(function(resolve, reject){
        setTimeout(function(){
            console.log("Your first prmise execute!");
            resolve();
        },1000)
    });
    promiceFirst.then(function(){
        console.log("your function is correct!");
    });*/


    /*new Promise((resolve, reject)=>{
        setTimeout((e)=>{
            const bol = true;
            if(!bol){
                resolve();
            }
            else{
                reject()
            }
            
        },1000)
    }).then((e)=>{
        console.log("Data executed!");
    }).catch(function(){
        console.log("Error exist!")
    })*/


    /*new Promise(function(resolve, reject){
        setTimeout(function(){
            const errors = false;
            if(!errors){
                console.log("Object successfully defines...");
                resolve({username: "Shehroz Ali", userId: 126});
            }
            else{
                reject("Error detected please correct this");
            }
        },1000)
    }).then(function(user){
        console.log(user)
    }).catch(function(errore){
        console.log(errore);
    }).finally(function(){
        console.log("Resolve and Rejected executed Successfully...");
    })*/


    const consumeData = new Promise(function(resolve, reject){
        setTimeout(function(){
            const crupt = true;
            if(!crupt){
                console.log("Object successfully created...!");
                resolve({username: "Shehroz Ali", userId: 126});
            }
            else{
                reject("something went wrong Please try again later...")
            }
        }, 1000)
    });
    async function consumeFunction() {
        try{
            const result = await consumeData;
            console.log(result)
        }

        catch(error){
            console.log(error)
        }
    }
    consumeFunction();


</script>
-->